### ISSUE TITLE
outernet_rtlsdr.grc:  AttributeError: 'module' object has no attribute 'swap_ff'

### ISSUE THREAD

**Issue by pavelmc** [daniestevez/gr-outernet#1]
Hi Dani, good work on this.

But I have problem here, I'm running over a Ubuntu 16.04 LTS with updated (today) repo and code from you gr-kiss / gr-outernet / free-outernet and dependencies...

When I open the outernet_rtlsdr.grc file all looks good and when I hit run an error came, log of grc is pasted below, I would appreciate any comments/help on this.

73 de CO7WT, Pavel.

===== grc log ==========================================
<<< Welcome to GNU Radio Companion 3.7.9 >>>

Preferences file: /home/pavel/.gnuradio/grc.conf
Block paths:
	/usr/local/share/gnuradio/grc/blocks
	/usr/share/gnuradio/grc/blocks
	/home/pavel/.grc_gnuradio

Loading: "/home/pavel/Documentos/Software/Github/gr-outernet/examples/outernet-rtlsdr.grc"
>>> Done

Showing: "/home/pavel/Documentos/Software/Github/gr-outernet/examples/outernet-rtlsdr.grc"

Generating: '/home/pavel/Documentos/Software/Github/gr-outernet/examples/outernet_rtlsdr.py'

Executing: /usr/bin/python -u /home/pavel/Documentos/Software/Github/gr-outernet/examples/outernet_rtlsdr.py

linux; GNU C++ version 5.3.1 20151219; Boost_105800; UHD_003.009.002-0-unknown

gr-osmosdr 0.1.4 (0.1.4) gnuradio 3.7.9
built-in source types: file osmosdr fcd rtl rtl_tcp uhd miri hackrf bladerf rfspace airspy redpitaya 
Using device #0 Realtek RTL2838UHIDIR
Found Elonics E4000 tuner
Using Volk machine: avx2_64_mmx_orc
Traceback (most recent call last):
  File "/home/pavel/Documentos/Software/Github/gr-outernet/examples/outernet_rtlsdr.py", line 438, in <module>
    main()
  File "/home/pavel/Documentos/Software/Github/gr-outernet/examples/outernet_rtlsdr.py", line 426, in main
    tb = top_block_cls()
  File "/home/pavel/Documentos/Software/Github/gr-outernet/examples/outernet_rtlsdr.py", line 233, in __init__
    self.outernet_swap_ff_1 = outernet.swap_ff()
AttributeError: 'module' object has no attribute 'swap_ff'

>>> Done
=====================================================

**Comment by daniestevez** [comment]
Hi Pavel,

I think that this is a problem with SWIG in Ubuntu 16.04. I've several people with this problem in many other out-of-tree modules. I don't have a proper solution and I don't have Ubuntu to try to replicate the problem. However, some advice: look very closely to all the output of `cmake` and `make` when compiling `gr-outernet`. For some reason, if there is a problem with SWIG, the toolchain complains but it doesn't stop compilation, thus producing a OOT module that doesn't work. Also, make sure that you run `ldconfig`.

Closing this, as it is not an specific problem with gr-outernet, but rather a problem with your particular distribution/GNU Radio/SWIG installation.

In any case, this thread can still be used for further troubleshooting.

**Comment by pavelmc** [comment]
Yo are absolutely right, my cmake command tell me this:

===== cmake output fragment =========
-- Checking for module SWIG
-- Disabling SWIG because version check failed.
===== fragment end ==================================

So I'm looking for the latest swig for independent compilation to see if it works that way, will report results here.

Saludos desde Cuba.

**Comment by pavelmc** [comment]
I found a solution to this, please update the README.md about it.

For Ubuntu 16.04 LTS user the must install swig 3.0 from the repo, as easy as that.

sudo apt install swig swig3.0

Compiling the sources in the github swig repo works also, but the repo solution is easier.

73 CO7WT.

**Comment by daniestevez** [comment]
I have just updated the README to include some information about this problem and its solution.
